### Computational Economics
Alexander Skorobogatov

# Seminar 4.1
This seminar is devoted to matrix operations using numpy. For related materials when preparing the assignments, please see [Topic 1](https://github.com/askorobogat/CompEcon/blob/main/Topic%201.%20Introduction%20to%20Python.ipynb).

### Matrix operations and linear system
1. Create a random square matrix $A$ and make sure that the respective linear system is solvable -- calculate the determinant, find the rank.
2. Introduce a vector of intercepts $b$.
3. Solve the system $Ax = b$ for the vector $x$.
4. Create a matrix of non full rank (e.g., a matrix 4 by 3 then adding a column being a linear combination of the three columns.
5. Make sure that the matrix is of non full rank.
6. Try solving this both via the matrix operations (the inverse of the matrix, etc.) and the numpy function.

### Market equilibrium
7. Using sympy introduce coef matrices for demand and supply and the respective intercept vectors. Find equilibrium price and quantiry vectors analytically.
8. Create a coefficient matrix for linear demand functions assuming that the goods are capable of substituting each other
9. Create a coefficient matrix for linear supply functions assuming a scarce resource available for using in the production of all the goods
10. Given these, assume some demands and supplies introducing the respective vectors
11. Solve for the market equilibrium

### Leontief model
The model is given by

$$ x = Ax + y $$

where $x$ is a gross output, $y$ is a net output, and $A$ is a coefficient matrix.  

12. Create a random positive semi-definite matrix $A$  
13. Create a random positive vector $y$. Given this, solve for $x$ and discuss.  
14. Create a random positive vector $x$. Given this, solve for $y$ and discuss.

### Matrix operations

In [4]:
# 1.1 Egor Titov

import numpy as np
import pandas as pd
from random import randint

n = randint(2, 9)
A = np.random.rand(n,  n)


det = np.linalg.det(A)
rank = np.linalg.matrix_rank(A)

print(f"System is solvable as\n\nMatrix determinant is {det}\nMatrix rank is {rank}")

System is solvable as

Matrix determinant is 0.2777781692602769
Matrix rank is 2


In [6]:
# 1.2-4 Egor Titov
b = np.random.rand(A.shape[0])

# 1.3
X = np.linalg.solve(A, b)

In [7]:
# 1.4 Alexander Skorobogatov
A = np.random.rand(4,3)
b_r = np.random.rand(3,1)
c4 = A@b_r
A2 = np.concatenate((A,c4), axis=1)
print(A)
print(A2)
np.linalg.matrix_rank(A2)

[[0.11028107 0.25447816 0.32600535]
 [0.2399776  0.11604024 0.58747348]
 [0.02553893 0.64023801 0.37280786]
 [0.21643416 0.26349953 0.20500232]]
[[0.11028107 0.25447816 0.32600535 0.31595826]
 [0.2399776  0.11604024 0.58747348 0.54042815]
 [0.02553893 0.64023801 0.37280786 0.34323881]
 [0.21643416 0.26349953 0.20500232 0.33715463]]


3

In [50]:
# 5 Alexander Skorobogatov
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(A2))
print(np.linalg.det(A2))
print(np.linalg.matrix_rank(A2[:3,:3]))
print(np.linalg.det(A2[:3,:3]))

3
3
-4.115108254154639e-12
3
1158.3000000000009


In [52]:
# 6 Alexander Skorobogatov
b = np.array([[2,3,6,1]]).T
print(np.linalg.inv(A2)@b)
print(np.linalg.solve(A2,b))

[[ 3.16074310e+14]
 [ 6.32148619e+14]
 [ 9.48222929e+14]
 [-3.16074310e+14]]
[[ 3.16074310e+14]
 [ 6.32148619e+14]
 [ 9.48222929e+14]
 [-3.16074310e+14]]


### Market equilibrium

In [77]:
# 7 Alexander Skorobogatov
from sympy import symbols,solve, Eq
A,B,s,d,p,q = symbols('A,B,s,d,p,q')
pd = A*q + d
ps = B*q + s
sol = Eq(s-d,solve(Eq(pd,ps),s-d)[0])
sol

Eq(-d + s, q*(A - B))

In [18]:
#Egor Titov, [10.10.2022 13:43]
#Task 2.1
import sympy as sym

A, B, s, d, p, q = sym.symbols('A,B,s,d,p,q')
P_d = A * q + d
P_s = B*  q + s 
solution = sym.Eq(s-d, sym.solve(sym.Eq(P_d, P_s), s-d)[0])
print(solution)


Eq(-d + s, q*(A - B))


In [19]:
# Vladislav Taltos 8-11
def random_matrix(n,positive=True,maxeigen=10):
    e=np.random.uniform(0,maxeigen,n) 
    r=np.random.uniform(0,1,n*n).reshape(n,n) 
    e = e if positive else -e
    A = np.diag(e)  
    return r @ A @ r.T 
n = 4
A = random_matrix(n, positive = False)
A_supply = A
A_supply[np.diag_indices(n)] = np.random.uniform(0, 10, n)
A = random_matrix(n, positive = True)
A_demand_sub = A
A_demand_sub[np.diag_indices(n)] = -np.random.uniform(0, 10, n)
d = np.array([250,]*n)
s = np.array([350,]*n)
prices = np.linalg.solve(A_demand_sub - A_supply, s-d)
quantities = A_demand_sub@prices + d
print(f"prices: {prices}")
print(f"quantities: {quantities}")

prices: [5.50229051 7.61911326 3.49623844 5.7415885 ]
quantities: [307.55692475 295.11050958 293.64657793 312.06380552]


### Leontief model

In [21]:
# Tatiana Fedorova 3.1-2
def random_matrix(n,positive=True,maxeigen=10):
    e=np.random.uniform(0,maxeigen,n) 
    r=np.random.uniform(0,1,n*n).reshape(n,n)
    e = e if positive else -e
    A = np.diag(e)  
    return r @ A @ r.T
A=random_matrix(3)
rand_y = np.random.rand(3,1)
rand_x = np.random.rand(3,1)
#Ax-x=y
#x(A-1)=y
B=A-1
#solve for x
x_solved = np.linalg.solve(B,rand_y)
x_solved

array([[-0.18911464],
       [ 0.34691522],
       [-0.0457736 ]])

In [26]:
# Vladislav Taltos, 3.1-3.3
def random_matrix(n,positive=True,maxeigen=10):
    e=np.random.uniform(0,maxeigen,n) 
    r=np.random.uniform(0,1,n*n).reshape(n,n) 
    e = e if positive else -e
    A = np.diag(e)  
    return r @ A @ r.T 
n = 3
A = random_matrix(n, positive = True)
def random_vector(n, positive=True, maxeigen = 10):
    b = np.random.uniform(0, maxeigen, n)
    b = b if positive else -b
    return b 
y = random_vector(n, positive=True)    
x = np.linalg.inv(1-A)@y
print(y)
print(x)

[1.26112664 7.88061699 2.05443793]
[ 14.57263902 -35.45041875  13.44268002]
