# Topic. 2. Stationary distribution for analysis of panel data: example 1
We will use panel data for real wages across countries

In [188]:
# Download a dataset

url1 = 'https://raw.githubusercontent.com/QuantEcon/lecture-python/master/source/_static/lecture_specific/pandas_panel/realwage.csv'

In [207]:
import numpy as np
import pandas as pd

# Display 6 columns for viewing purposes
pd.set_option('display.max_columns', 6)

# Reduce decimal points to 2
pd.options.display.float_format = '{:,.2f}'.format

realwage = pd.read_csv(url1)

In [208]:
# the numbers of rows and columns
print(realwage.shape)
# More info
realwage.info()

(1408, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1408 non-null   int64  
 1   Time        1408 non-null   object 
 2   Country     1408 non-null   object 
 3   Series      1408 non-null   object 
 4   Pay period  1408 non-null   object 
 5   value       1340 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 66.1+ KB


In [209]:
# Take a look at the table
realwage.head()

Unnamed: 0        Time  Country                                    Series  \
0           0  2006-01-01  Ireland  In 2015 constant prices at 2015 USD PPPs   
1           1  2007-01-01  Ireland  In 2015 constant prices at 2015 USD PPPs   
2           2  2008-01-01  Ireland  In 2015 constant prices at 2015 USD PPPs   
3           3  2009-01-01  Ireland  In 2015 constant prices at 2015 USD PPPs   
4           4  2010-01-01  Ireland  In 2015 constant prices at 2015 USD PPPs   

  Pay period     value  
0     Annual 17,132.44  
1     Annual 18,100.92  
2     Annual 17,747.41  
3     Annual 18,580.14  
4     Annual 18,755.83

Variable of interest 'value' has four versions across two dimensions 'Series' and 'Pay period'. Let's check them:

In [210]:
print(realwage['Series'].unique())
print(realwage['Pay period'].unique())

['In 2015 constant prices at 2015 USD PPPs'
 'In 2015 constant prices at 2015 USD exchange rates']
['Annual' 'Hourly']


In [244]:
# Let's choose USD PPPs and hourly (and rename df)
w = realwage[realwage['Series'].isin([realwage['Series'].unique()[0]])
         & realwage['Pay period'].isin([realwage['Pay period'].unique()[1]])]
w

Unnamed: 0        Time     Country  \
11            11  2006-01-01     Ireland   
12            12  2007-01-01     Ireland   
13            13  2008-01-01     Ireland   
14            14  2009-01-01     Ireland   
15            15  2010-01-01     Ireland   
...          ...         ...         ...   
1381        1381  2012-01-01  Costa Rica   
1382        1382  2013-01-01  Costa Rica   
1383        1383  2014-01-01  Costa Rica   
1384        1384  2015-01-01  Costa Rica   
1385        1385  2016-01-01  Costa Rica   

                                        Series Pay period  value  
11    In 2015 constant prices at 2015 USD PPPs     Hourly   8.24  
12    In 2015 constant prices at 2015 USD PPPs     Hourly   8.70  
13    In 2015 constant prices at 2015 USD PPPs     Hourly   8.53  
14    In 2015 constant prices at 2015 USD PPPs     Hourly   8.93  
15    In 2015 constant prices at 2015 USD PPPs     Hourly   9.02  
...                                        ...        ...    ...  
1381  In 2015 constant prices at 2015 USD PPPs     Hourly    NaN  
1382  In 2015 constant prices at 2015 USD PPPs     Hourly    NaN  
1383  In 2015 constant prices at 2015 USD PPPs     Hourly   3.40  
1384  In 2015 constant prices at 2015 USD PPPs     Hourly   3.60  
1385  In 2015 constant prices at 2015 USD PPPs     Hourly   3.70  

[352 rows x 6 columns]

In [245]:
# Keep i and j indeces, and the variable of interest
w = w[['Time', 'Country', 'value']]
w

Time     Country  value
11    2006-01-01     Ireland   8.24
12    2007-01-01     Ireland   8.70
13    2008-01-01     Ireland   8.53
14    2009-01-01     Ireland   8.93
15    2010-01-01     Ireland   9.02
...          ...         ...    ...
1381  2012-01-01  Costa Rica    NaN
1382  2013-01-01  Costa Rica    NaN
1383  2014-01-01  Costa Rica   3.40
1384  2015-01-01  Costa Rica   3.60
1385  2016-01-01  Costa Rica   3.70

[352 rows x 3 columns]

In [246]:
# For convenience, rename indeces as normally done
w.rename(columns = {'Time' : 't', 'Country' : 'id'}, inplace = True)
w

C:\Users\Alex\AppData\Local\Temp\ipykernel_108\1485330872.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w.rename(columns = {'Time' : 't', 'Country' : 'id'}, inplace = True)


t          id  value
11    2006-01-01     Ireland   8.24
12    2007-01-01     Ireland   8.70
13    2008-01-01     Ireland   8.53
14    2009-01-01     Ireland   8.93
15    2010-01-01     Ireland   9.02
...          ...         ...    ...
1381  2012-01-01  Costa Rica    NaN
1382  2013-01-01  Costa Rica    NaN
1383  2014-01-01  Costa Rica   3.40
1384  2015-01-01  Costa Rica   3.60
1385  2016-01-01  Costa Rica   3.70

[352 rows x 3 columns]

In [247]:
# Drop missing values (and rename df)
print(w['value'].isna().sum())
w = w.dropna(axis='index', subset=['value'])
w

17


t          id  value
11    2006-01-01     Ireland   8.24
12    2007-01-01     Ireland   8.70
13    2008-01-01     Ireland   8.53
14    2009-01-01     Ireland   8.93
15    2010-01-01     Ireland   9.02
...          ...         ...    ...
1340  2015-01-01    Colombia   2.40
1341  2016-01-01    Colombia   2.40
1383  2014-01-01  Costa Rica   3.40
1384  2015-01-01  Costa Rica   3.60
1385  2016-01-01  Costa Rica   3.70

[335 rows x 3 columns]

Then we need a categorical variable to break down countries into income groups  
We can do it based on the wage quartiles

In [248]:
# Create dummies for the quartiles
for i in range(1,4): exec("c"+str(i)+" = w[w['t'] == w['t'].unique()[0]]['value'].describe()[i+3]")
print(c1)
print(c2)
print(c3)

2.538069975
4.44781495
7.256152524999999


In [254]:
w = w.sort_values(by=['id','t'])
w

t             id  value
99   2006-01-01      Australia  10.33
100  2007-01-01      Australia  10.67
101  2008-01-01      Australia  10.48
102  2009-01-01      Australia  10.62
103  2010-01-01      Australia  10.57
..          ...            ...    ...
545  2012-01-01  United States   7.48
546  2013-01-01  United States   7.38
547  2014-01-01  United States   7.26
548  2015-01-01  United States   7.25
549  2016-01-01  United States   7.16

[335 rows x 3 columns]

In [256]:
# Using the dummies create the categorical variable 'cat'
w.loc[(w['value'] < c1), 'cat'] = 1
w.loc[(w['value'] >= c1) & (w['value'] < c2), 'cat'] = 2
w.loc[(w['value'] >= c2) & (w['value'] < c3), 'cat'] = 3
w.loc[w['value'] >= c3, 'cat'] = 4
df = w
df

t             id  value  cat
99   2006-01-01      Australia  10.33 4.00
100  2007-01-01      Australia  10.67 4.00
101  2008-01-01      Australia  10.48 4.00
102  2009-01-01      Australia  10.62 4.00
103  2010-01-01      Australia  10.57 4.00
..          ...            ...    ...  ...
545  2012-01-01  United States   7.48 4.00
546  2013-01-01  United States   7.38 4.00
547  2014-01-01  United States   7.26 4.00
548  2015-01-01  United States   7.25 3.00
549  2016-01-01  United States   7.16 3.00

[335 rows x 4 columns]

In [257]:
df['trans'] = df.cat.shift(-1).where(df.id.eq(df.id.shift(-1)))
df

t             id  value  cat  trans
99   2006-01-01      Australia  10.33 4.00   4.00
100  2007-01-01      Australia  10.67 4.00   4.00
101  2008-01-01      Australia  10.48 4.00   4.00
102  2009-01-01      Australia  10.62 4.00   4.00
103  2010-01-01      Australia  10.57 4.00   4.00
..          ...            ...    ...  ...    ...
545  2012-01-01  United States   7.48 4.00   4.00
546  2013-01-01  United States   7.38 4.00   4.00
547  2014-01-01  United States   7.26 4.00   3.00
548  2015-01-01  United States   7.25 3.00   3.00
549  2016-01-01  United States   7.16 3.00    NaN

[335 rows x 5 columns]

In [258]:
# Numbers of transitions across the groups
tr = pd.crosstab(df.cat, df.trans)
tr

trans  1.00  2.00  3.00  4.00
cat                          
1.00     47     4     0     0
2.00      0    87     4     0
3.00      0     0    64     3
4.00      0     0     1    93

In [259]:
# Compare with the data
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df)

               t                  id  value  cat  trans
99    2006-01-01           Australia  10.33 4.00   4.00
100   2007-01-01           Australia  10.67 4.00   4.00
101   2008-01-01           Australia  10.48 4.00   4.00
102   2009-01-01           Australia  10.62 4.00   4.00
103   2010-01-01           Australia  10.57 4.00   4.00
104   2011-01-01           Australia  10.65 4.00   4.00
105   2012-01-01           Australia  10.80 4.00   4.00
106   2013-01-01           Australia  10.83 4.00   4.00
107   2014-01-01           Australia  10.86 4.00   4.00
108   2015-01-01           Australia  10.99 4.00   4.00
109   2016-01-01           Australia  11.12 4.00    NaN
1067  2006-01-01             Belgium  10.09 4.00   4.00
1068  2007-01-01             Belgium  10.22 4.00   4.00
1069  2008-01-01             Belgium  10.27 4.00   4.00
1070  2009-01-01             Belgium  10.62 4.00   4.00
1071  2010-01-01             Belgium  10.46 4.00   4.00
1072  2011-01-01             Belgium  10.37 4.00

Now let's create a transition probability matrix from the number table.

In [260]:
# First create a zero matrix in the form of four lists
N = 4
M = 4
m = []
for i in range(N):
    m.append([0]*M)
m

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [261]:
# Then fill the cells with the probabilities
for i in range(1,5):
    for j in range(1,5):
        m[i-1][j-1] = tr.loc[i,j]/tr.loc[i].sum()

# Make this as numpay array
m = np.array(m)
m

array([[0.92156863, 0.07843137, 0.        , 0.        ],
       [0.        , 0.95604396, 0.04395604, 0.        ],
       [0.        , 0.        , 0.95522388, 0.04477612],
       [0.        , 0.        , 0.0106383 , 0.9893617 ]])

Now 'm' is a transition probability matrix  
Having this we can find a future distribution based on an initial distribution

In [262]:
# Assume initially fully exactly equal distribution
dist1 = [[0.25],[0.25],[0.25],[0.25]]

In [263]:
# Then in the next period we have
np.transpose(m)@dist1

array([[0.23039216],
       [0.25861883],
       [0.25245456],
       [0.25853446]])

In [264]:
# or
np.transpose(dist1)@m

array([[0.23039216, 0.25861883, 0.25245456, 0.25853446]])

In [265]:
# In two periods
np.transpose(dist1)@m@m

array([[0.21232218, 0.26532094, 0.25526885, 0.26708802]])

In [266]:
# The same using numpy function for matrix powers
np.transpose(dist1)@np.linalg.matrix_power(m,2)

array([[0.21232218, 0.26532094, 0.25526885, 0.26708802]])

In [267]:
# Distribution in 70 periods
np.transpose(dist1)@np.linalg.matrix_power(m,70)

array([[0.00082201, 0.0333347 , 0.23713066, 0.72871263]])

In [268]:
# Let's check the tendency up to 70th period
a = np.transpose(dist1)
for i in range(0,70):
    i = a@m
    a = i
    print(i)

[[0.23039216 0.25861883 0.25245456 0.25853446]]
[[0.21232218 0.26532094 0.25526885 0.26708802]]
[[0.19566946 0.27031121 0.25834272 0.27567661]]
[[0.18032284 0.27377602 0.26158968 0.28431147]]
[[0.16617987 0.27588488 0.26493541 0.29299985]]
[[0.15314616 0.27679178 0.26831646 0.30174561]]
[[0.14113469 0.27663658 0.27167902 0.31054972]]
[[0.1300653  0.27554611 0.27497785 0.31941073]]
[[0.1198641  0.2736354  0.27817532 0.32832518]]
[[0.110463   0.27100857 0.28124046 0.33728797]]
[[0.10179923 0.26775987 0.28414823 0.34629266]]
[[0.09381498 0.26397446 0.28687881 0.35533175]]
[[0.08645694 0.25972923 0.28941689 0.36439694]]
[[0.07967601 0.25509349 0.29175115 0.37347935]]
[[0.07342691 0.25012969 0.29387376 0.38256965]]
[[0.06766793 0.24489395 0.29577983 0.39165828]]
[[0.06236065 0.23943667 0.2974671  0.40073558]]
[[0.05746961 0.23380301 0.29893551 0.40979186]]
[[0.05296219 0.22803338 0.30018689 0.41881754]]
[[0.0488083  0.22216383 0.30122463 0.42780324]]
[[0.04498019 0.21622649 0.3020535  0.436

### Solutions
Now, to better understand the respective algebra, let's calculate the stationary distribution manually solving the linear system

In [269]:
# 1. Transpose TM and subtract the identity matrix
mt_e = np.transpose(m) - np.identity(4)
mt_e[3] = np.ones(4)
mt_e

array([[-0.07843137,  0.        ,  0.        ,  0.        ],
       [ 0.07843137, -0.04395604,  0.        ,  0.        ],
       [ 0.        ,  0.04395604, -0.04477612,  0.0106383 ],
       [ 1.        ,  1.        ,  1.        ,  1.        ]])

In [270]:
# 2. Invert the result
mt_e_inv = np.linalg.inv(mt_e)
mt_e_inv

array([[-1.27500000e+01, -3.55271368e-15,  0.00000000e+00,
        -5.55111512e-17],
       [-2.27500000e+01, -2.27500000e+01, -0.00000000e+00,
        -0.00000000e+00],
       [-1.12306590e+01, -1.36783668e+01, -1.80458453e+01,
         1.91977077e-01],
       [ 4.67306590e+01,  3.64283668e+01,  1.80458453e+01,
         8.08022923e-01]])

In [271]:
# 3. Prepare the right-hand side columns
v = np.zeros(4)
v[3] = 1
v

array([0., 0., 0., 1.])

In [272]:
# 4. Solve
res = mt_e_inv@np.transpose(v)
res

array([-5.55111512e-17,  0.00000000e+00,  1.91977077e-01,  8.08022923e-01])

A bit different way

In [273]:
s = m.shape[0]  # dimension of the problem
A = np.ones((s+1,s+1))  # square matrix of ones
A[:-1,:-1] = np.eye(s)-m.T
b = np.ones(s+1)
b[-1]=2

In [274]:
A

array([[ 0.07843137,  0.        ,  0.        ,  0.        ,  1.        ],
       [-0.07843137,  0.04395604,  0.        ,  0.        ,  1.        ],
       [ 0.        , -0.04395604,  0.04477612, -0.0106383 ,  1.        ],
       [ 0.        ,  0.        , -0.04477612,  0.0106383 ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [275]:
b

array([1., 1., 1., 1., 2.])

In [276]:
np.linalg.inv(A)@b.T

array([ 1.77635684e-15, -4.09132699e-15,  1.91977077e-01,  8.08022923e-01,
        1.00000000e+00])

In [277]:
np.linalg.solve(A,b)

array([2.45880561e-15, 3.20333182e-15, 1.91977077e-01, 8.08022923e-01,
       1.00000000e+00])

Or just apply the functions

In [278]:
def stationary_linalg(P,psi0=[None,]):
    '''Computes stationary distribution for the Markov chain given by transition probability
    matrix P. Method: linear solver.
    '''
    if psi0[0]==None:
        # degenrate initial distribution
        psi0 = [0,]*P.shape[0]
        psi0[0]=1.0
    P,psi0 = np.asarray(P),np.asarray(psi0)  # convert to np arrays (in case lists were passed)
    assert np.all(np.abs(P.sum(axis=1)-1)<1e-10), 'Passed P is not stochastic matrix'
    assert np.abs(psi0.sum()-1)<1e-10, 'Passed probabilities do not sum up to one'
    m = P.shape[0]  # dimension of the problem
    A = np.ones((m+1,m+1))  # square matrix of ones
    A[:-1,:-1] = np.eye(m)-P.T
    b = np.ones(m+1)
    b[-1]=2
    res = np.linalg.solve(A,b)
    return res[:-1]

print(stationary_linalg(m))

[2.45880561e-15 3.20333182e-15 1.91977077e-01 8.08022923e-01]


In [279]:
def stationary_sa(P,psi0=[None,],tol=1e-6,maxiter=80,callback=None):
    '''Computes stationary distribution for the Markov chain given by transition probability
    matrix P, with given maximum number of iterations, and convergence tolerance.
    callback function is called at each iteration if given.
    Method: successive approximations
    '''
    if psi0[0]==None:
        # degenrate initial distribution
        psi0 = [0,]*P.shape[0]
        psi0[0]=1.0
    P,psi0 = np.asarray(P),np.asarray(psi0)  # convert to np arrays (in case lists were passed)
    assert np.all(np.abs(P.sum(axis=1)-1)<1e-10), 'Passed P is not stochastic matrix'
    assert np.abs(psi0.sum()-1)<1e-10, 'Passed probabilities do not sum up to one'
    for i in range(maxiter):  # main loop
        psi1 = psi0 @ P  # update approximation of psi^star
        err = np.amax(abs(psi0-psi1))  # error is the max absolute deviation element-wise
        if callback != None: callback(err=err,iter=i,psi=psi1)
        if err<tol:
            break  # break out if converged
        psi0 = psi1  # get ready to the next iteration
    else:
        raise RuntimeError('Failed to converge in %d iterations'%maxiter)
    return psi1

def printme(**kwargs):
    print('iter %d, psi = %r'%(kwargs['iter'],kwargs['psi']))
stationary_sa(m,callback=printme)

iter 0, psi = array([0.92156863, 0.07843137, 0.        , 0.        ])
iter 1, psi = array([0.84928874, 0.14726373, 0.00344753, 0.        ])
iter 2, psi = array([7.82677854e-01, 2.07401482e-01, 9.76629679e-03, 1.54367143e-04])
iter 3, psi = array([7.21291356e-01, 2.59671432e-01, 1.84471908e-02, 5.90021811e-04])
iter 4, psi = array([0.66471948, 0.30482917, 0.0290416 , 0.00140974])
iter 5, psi = array([0.61258462, 0.34356495, 0.04115531, 0.00269511])
iter 6, psi = array([0.56453877, 0.37650905, 0.05444297, 0.00450922])
iter 7, psi = array([0.52026122, 0.40423675, 0.06860304, 0.00689899])
iter 8, psi = array([0.47945642, 0.4272729 , 0.0833733 , 0.00989737])
iter 9, psi = array([0.44185199, 0.4460961 , 0.09852669, 0.01352522])
iter 10, psi = array([0.40719693, 0.46114254, 0.11386755, 0.01779297])
iter 11, psi = array([0.37525992, 0.47280955, 0.12922829, 0.02270223])
iter 12, psi = array([0.34582777, 0.48145887, 0.1444663 , 0.02824706])
iter 13, psi = array([0.31870402, 0.48741959, 0.1594611

RuntimeError: Failed to converge in 80 iterations